import asyncio
import json
import re
from typing import List, AsyncGenerator
from models.schemas import SourceChunk, SubQuestion, ResearchDepth
from services.ollama import ollama_service

WRITER_SYSTEM = """You are an expert research writer. You will be given a list of research sub-questions and source materials.
Your task is to write a comprehensive, well-structured markdown research report.

CRITICAL RULES:
1. Only use information from the provided sources. Never invent facts.
2. Cite sources using [1], [2], etc. corresponding to the source IDs provided.
3. Structure the report with clear markdown headers (##, ###).
4. Begin with an Executive Summary section.
5. Cover each sub-question in a dedicated section.
6. End with a Conclusions section.
7. Use bullet points, bold text, and tables where appropriate.
8. The report should be 600-1000 words."""


def _build_writer_prompt(
    query: str,
    sub_questions: List[SubQuestion],
    sources: List[SourceChunk],
) -> str:
    sources_text = "\n\n".join([
        f"[{s.id}] {s.title} ({s.domain})\n"
        f"URL: {s.url}\n"
        f"Date: {s.date or 'N/A'}\n"
        f"Content: {s.content[:800]}"
        for s in sources
    ])

    questions_text = "\n".join([f"{sq.id}. {sq.question}" for sq in sub_questions])

    return f"""Research Topic: "{query}"

Sub-questions to address:
{questions_text}

Sources:
{sources_text}

Write a comprehensive research report addressing all sub-questions using the sources above."""


def _mock_report(query: str, sub_questions: List[SubQuestion], sources: List[SourceChunk]) -> str:
    sections = []
    sections.append(f"# {query.title()}\n")
    sections.append(f"*Generated by Dvelve · {len(sources)} sources cited*\n")

    # Executive Summary
    sections.append("## Executive Summary\n")
    top_source = sources[0] if sources else None
    if top_source:
        sections.append(
            f"This report provides a comprehensive analysis of **{query}**, drawing from {len(sources)} authoritative sources. "
            f"Key findings highlight significant recent developments, including insights from {top_source.domain} [1] "
            f"and other leading institutions. The research synthesizes current knowledge, identifies key trends, "
            f"and outlines future trajectories for this rapidly evolving field.\n"
        )

    # Sections for each sub-question
    for i, sq in enumerate(sub_questions):
        sections.append(f"## {sq.question}\n")
        if sources:
            src_idx = i % len(sources)
            src = sources[src_idx]
            next_src = sources[(src_idx + 1) % len(sources)] if len(sources) > 1 else src
            sections.append(
                f"{src.snippet} [{src.id}]\n\n"
                f"Further research from {next_src.domain} indicates: {next_src.snippet} [{next_src.id}]\n\n"
                f"**Key Points:**\n"
                f"- Significant developments have been observed in this area\n"
                f"- Multiple stakeholders are actively engaged in advancing the field\n"
                f"- Data indicates growing momentum and investment\n"
            )
        else:
            sections.append(
                f"This section addresses the question: *{sq.question}*\n\n"
                f"Based on available knowledge, this is an active area of research with significant implications.\n"
                f"**Key Points:**\n"
                f"- Significant developments have been observed in this area\n"
                f"- Multiple stakeholders are actively engaged in advancing the field\n"
            )

    # Conclusions
    sections.append("## Conclusions\n")
    sections.append(
        f"The analysis of **{query}** reveals a dynamic and rapidly evolving landscape. "
        f"Evidence from {len(sources)} sources converges on several key themes:\n\n"
        f"1. **Accelerating Progress** — The pace of development continues to increase year over year\n"
        f"2. **Cross-Disciplinary Impact** — Advances in this field are reshaping adjacent domains\n"
        f"3. **Future Outlook** — Projections suggest continued growth with significant milestones expected in the next 2-5 years\n\n"
        f"Organizations and researchers in this space should monitor these developments closely and adapt strategies accordingly.\n"
    )

    # References
    sections.append("## References\n")
    for s in sources:
        sections.append(f"[{s.id}] {s.title}. *{s.domain}*. {s.date or '2024'}. [{s.url}]({s.url})\n")

    return "\n".join(sections)


async def run_writer_stream(
    query: str,
    sub_questions: List[SubQuestion],
    sources: List[SourceChunk],
    model: str,
    offline_mode: bool,
) -> AsyncGenerator[str, None]:
    """Yields markdown tokens one by one for SSE streaming."""
    if not offline_mode:
        try:
            available = await ollama_service.is_available()
            if available:
                prompt = _build_writer_prompt(query, sub_questions, sources)
                token_count = 0
                async for token in ollama_service.generate_stream(
                    model, prompt, system=WRITER_SYSTEM
                ):
                    token_count += 1
                    yield token
                if token_count > 0:
                    return
                # Ollama returned no tokens — fall through to mock
        except Exception:
            pass

    # Mock streaming: yield the mock report character by character in chunks
    report = _mock_report(query, sub_questions, sources)
    chunk_size = 8
    for i in range(0, len(report), chunk_size):
        yield report[i:i + chunk_size]
        await asyncio.sleep(0.02)  # simulate token latency
